const encoder=new TextEncoder();
const hex=b=>Array.from(new Uint8Array(b),n=>n.toString(16).padStart(2,'0')).join('');
function visualQuality(annotation){
  const words=[];for(const page of annotation?.pages||[])for(const block of page.blocks||[])for(const paragraph of block.paragraphs||[])for(const word of paragraph.words||[]){
    const v=word.boundingBox?.vertices||[], ys=v.map(p=>p.y||0);const height=Math.max(...ys)-Math.min(...ys);
    if(height>0)words.push({height,confidence:typeof word.confidence==='number'?word.confidence:null});
  }
  if(words.length<2)return null;
  const heights=words.map(w=>w.height),mean=heights.reduce((a,b)=>a+b,0)/heights.length;
  const variation=Math.sqrt(heights.reduce((a,h)=>a+(h-mean)**2,0)/heights.length)/mean;
  const sizeConsistency=Math.max(0,Math.min(100,Math.round(100*(1-variation/.65))));
  const confidenceWords=words.filter(w=>w.confidence!==null);
  const recognitionConfidence=confidenceWords.length?Math.round(100*confidenceWords.reduce((a,w)=>a+w.confidence,0)/confidenceWords.length):null;
  const score=recognitionConfidence===null?sizeConsistency:Math.round(sizeConsistency*.55+recognitionConfidence*.45);
  return {score,sizeConsistency,recognitionConfidence,wordCount:words.length};
}
async function digest(v){return hex(await crypto.subtle.digest('SHA-256',typeof v==='string'?encoder.encode(v):v));}
async function signature(v,s){const k=await crypto.subtle.importKey('raw',encoder.encode(s),{name:'HMAC',hash:'SHA-256'},false,['sign']);return hex(await crypto.subtle.sign('HMAC',k,encoder.encode(v)));}
async function passwordHash(password,salt,iterations=210000){const key=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:Uint8Array.from(salt.match(/../g).map(x=>parseInt(x,16))),iterations},key,256));}
function randomHex(bytes=16){const value=new Uint8Array(bytes);crypto.getRandomValues(value);return hex(value);}
function normalizedUsername(value){return typeof value==='string'?value.trim().toLowerCase():'';}
function normalizedClassCode(value){return typeof value==='string'?value.trim().toUpperCase():'';}
function equal(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return !d;}
function json(data,status=200,extra={}){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...extra}});}
async function body(req,limit=8192){if(!req.headers.get('Content-Type')?.startsWith('application/json'))throw Error('요청 형식을 확인해주세요.');const raw=await req.text();if(raw.length>limit)throw Error('요청이 너무 큽니다.');try{return JSON.parse(raw)}catch{throw Error('요청 내용을 확인해주세요.');}}
export function createHandler(env,fetcher=fetch){
  const signingKey=env.SESSION_SECRET||env.CLASS_CODE;
  async function rpc(name,args={}){const r=await fetcher(env.SUPABASE_URL+'/rest/v1/rpc/'+name,{method:'POST',headers:{'Content-Type':'application/json',apikey:env.SUPABASE_SERVICE_ROLE_KEY,...(env.SUPABASE_SERVICE_ROLE_KEY.startsWith('sb_secret_')?{}:{Authorization:'Bearer '+env.SUPABASE_SERVICE_ROLE_KEY})},body:JSON.stringify(args),signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('database unavailable');const t=await r.text();return t?JSON.parse(t):null;}
  async function db(path,options={}){const r=await fetcher(env.SUPABASE_URL+'/rest/v1/'+path,{...options,headers:{'Content-Type':'application/json',apikey:env.SUPABASE_SERVICE_ROLE_KEY,...(env.SUPABASE_SERVICE_ROLE_KEY.startsWith('sb_secret_')?{}:{Authorization:'Bearer '+env.SUPABASE_SERVICE_ROLE_KEY}),...(options.headers||{})},signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('database unavailable');const t=await r.text();return t?JSON.parse(t):null;}
  async function limited(bucket,max,expires){return rpc('pildam_throttle',{p_bucket:bucket,p_max:max,p_expiry:new Date(expires).toISOString()});}
  async function auth(req){const token=req.headers.get('X-Pildam-Session');if(!token||!signingKey)return null;const [role,subject,nonce,expiry,sig]=token.split('.');if(!/^(student|teacher)$/.test(role)||!/^[0-9a-f-]{36}$/.test(subject)||!/^[0-9a-f]{32}$/.test(nonce)||!/^\d{13}$/.test(expiry)||Number(expiry)<Date.now())return null;const value=[role,subject,nonce,expiry].join('.');if(!equal(sig,await signature(value,signingKey)))return null;return {role,subject,id:nonce,csrf:await signature('csrf.'+value,signingKey)};}
  async function issue(role,subject){const nonce=crypto.randomUUID().replaceAll('-',''),expiry=String(Date.now()+8*3600000),value=[role,subject,nonce,expiry].join('.');return value+'.'+await signature(value,signingKey);}
  async function classById(id){const rows=await db('pildam_classes?select=id,teacher_id,student_code,title,content,accuracy_weight&id=eq.'+encodeURIComponent(id));return rows?.[0]||null;}
  async function teacherClass(teacherId){const rows=await db('pildam_classes?select=id,teacher_id,student_code,title,content,accuracy_weight&teacher_id=eq.'+encodeURIComponent(teacherId));return rows?.[0]||null;}
  async function handle(req){const path=new URL(req.url).pathname.split('/').pop(),now=Date.now(),a=await auth(req);
    if(!signingKey||!env.SUPABASE_SERVICE_ROLE_KEY)return json({error:'선생님이 수업 설정을 준비하고 있어요.'},503);
    if(path==='status'&&req.method==='GET')return json({requiresLogin:true,authenticated:!!a,role:a?.role||null,configured:!!env.GOOGLE_VISION_API_KEY,teacherReady:!!env.TEACHER_CODE,registrationReady:!!env.TEACHER_INVITE_CODE,token:a?.csrf||null});
    if(path==='assignment'&&req.method==='GET'){if(!a)return json({error:'수업 코드를 다시 입력해주세요.'},401);const c=a.role==='teacher'?await teacherClass(a.subject):await classById(a.subject);if(!c)return json({error:'수업을 찾지 못했어요. 다시 로그인해주세요.'},404);return json({assignment:{title:c.title,content:c.content},accuracyWeight:c.accuracy_weight});}
    if(path==='settings'&&req.method==='GET'){if(!a||a.role!=='teacher')return json({error:'교사 계정으로 다시 들어와주세요.'},401);const c=await teacherClass(a.subject);if(!c)return json({error:'수업 설정을 찾지 못했어요.'},404);return json({hasStudentCode:!!c.student_code,studentCode:c.student_code,accuracyWeight:c.accuracy_weight});}
    if(req.method!=='POST')return json({error:'찾을 수 없는 요청입니다.'},404);
    if(path==='register'){if(!env.TEACHER_INVITE_CODE)return json({error:'교사 가입 기능을 준비하고 있어요.'},503);const data=await body(req),username=normalizedUsername(data.username),password=data.password,invite=data.inviteCode;if(!equal(await digest(String(invite||'')),await digest(env.TEACHER_INVITE_CODE)))return json({error:'교사 가입용 초대 코드를 확인해주세요.'},401);if(!/^[a-z0-9._-]{4,32}$/.test(username))return json({error:'아이디는 영문 소문자, 숫자, 점, 밑줄로 4~32자 입력해주세요.'},400);if(typeof password!=='string'||password.length<10||password.length>128)return json({error:'비밀번호는 10자 이상으로 입력해주세요.'},400);const existing=await db('pildam_teachers?select=id&username=eq.'+encodeURIComponent(username));if(existing?.length)return json({error:'이미 사용 중인 아이디예요.'},409);const salt=randomHex(),password_hash=await passwordHash(password,salt),created=await db('pildam_teachers',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({username,password_salt:salt,password_hash,password_iterations:210000})});const teacher=created?.[0];if(!teacher)return json({error:'교사 계정을 만들지 못했어요.'},503);await db('pildam_classes',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({teacher_id:teacher.id})});return json({ok:true,session:await issue('teacher',teacher.id)});}
    if(path==='login'){const data=await body(req),code=normalizedClassCode(data.code);if(code.length<4)return json({error:'수업 코드를 확인해주세요.'},401);const classes=await db('pildam_classes?select=id&student_code=eq.'+encodeURIComponent(code)),c=classes?.[0];if(!c){if(!await limited('login-failed:student:'+Math.floor(now/600000),120,now+1200000))return json({error:'잘못된 코드 입력이 너무 많아요. 잠시 후 다시 시도해주세요.'},429);return json({error:'수업 코드를 확인해주세요.'},401);}return json({ok:true,session:await issue('student',c.id)});}
    if(path==='teacher-login'){const data=await body(req),username=normalizedUsername(data.username),password=data.password;if(!username&&typeof data.code==='string'&&env.TEACHER_CODE&&equal(await digest(data.code),await digest(env.TEACHER_CODE)))return json({ok:true,session:await issue('teacher','00000000-0000-0000-0000-000000000001')});const rows=/^[a-z0-9._-]{4,32}$/.test(username)?await db('pildam_teachers?select=id,password_salt,password_hash,password_iterations&username=eq.'+encodeURIComponent(username)):[],teacher=rows?.[0],valid=teacher&&typeof password==='string'&&equal(await passwordHash(password,teacher.password_salt,teacher.password_iterations),teacher.password_hash);if(!valid){if(!await limited('login-failed:teacher:'+Math.floor(now/600000),120,now+1200000))return json({error:'잘못된 로그인 시도가 너무 많아요. 잠시 후 다시 시도해주세요.'},429);return json({error:'아이디와 비밀번호를 확인해주세요.'},401);}return json({ok:true,session:await issue('teacher',teacher.id)});}
    if(path==='assignment'){if(!a||a.role!=='teacher'||!equal(req.headers.get('X-App-Token'),a.csrf))return json({error:'교사 계정으로 다시 들어와주세요.'},401);const data=await body(req);if(typeof data.title!=='string'||typeof data.content!=='string'||!data.title.trim()||data.title.length>80||data.content.trim().length>1000)return json({error:'제목은 80자, 연습 글은 1,000자 이내로 입력해주세요.'},400);await db('pildam_classes?teacher_id=eq.'+encodeURIComponent(a.subject),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({title:data.title.trim(),content:data.content.trim(),updated_at:new Date().toISOString()})});const c=await teacherClass(a.subject);return json({assignment:{title:c.title,content:c.content}});}
    if(path==='settings'){if(!a||a.role!=='teacher'||!equal(req.headers.get('X-App-Token'),a.csrf))return json({error:'교사 계정으로 다시 들어와주세요.'},401);const data=await body(req),next={accuracy_weight:Number(data.accuracyWeight),updated_at:new Date().toISOString()};if(!Number.isInteger(next.accuracy_weight)||next.accuracy_weight<50||next.accuracy_weight>90)return json({error:'문장 일치도 비율은 50%에서 90% 사이로 정해주세요.'},400);if(data.studentCode!==undefined){const code=normalizedClassCode(data.studentCode);if(code.length<4||code.length>32)return json({error:'학생용 수업 코드는 4자에서 32자 사이로 입력해주세요.'},400);const used=await db('pildam_classes?select=id,teacher_id&student_code=eq.'+encodeURIComponent(code));if(used?.some(c=>c.teacher_id!==a.subject))return json({error:'다른 수업에서 사용 중인 코드예요. 다른 코드를 정해주세요.'},409);next.student_code=code;}await db('pildam_classes?teacher_id=eq.'+encodeURIComponent(a.subject),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(next)});const c=await teacherClass(a.subject);return json({hasStudentCode:!!c.student_code,studentCode:c.student_code,accuracyWeight:c.accuracy_weight});}
    if(path!=='ocr')return json({error:'찾을 수 없는 요청입니다.'},404);
    if(!a)return json({error:'수업 코드를 다시 입력해주세요.'},401);
    if(!equal(req.headers.get('X-App-Token'),a.csrf))return json({error:'페이지를 새로고침하고 수업 코드를 다시 입력해주세요.'},403);
    if(!env.GOOGLE_VISION_API_KEY)return json({error:'선생님이 인식 서비스를 연결하고 있어요.'},503);
    if(!await limited('ocr:'+a.id+':'+Math.floor(now/60000),3,now+120000))return json({error:'1분 후 다시 분석해주세요.'},429);
    const data=await body(req,8100000),content=data.image;if(typeof content!=='string'||content.length>8000000||!/^\/9j\/[A-Za-z0-9+/]*={0,2}$/.test(content))return json({error:'사진 형식을 확인해주세요.'},400);
    let raw;try{raw=Uint8Array.from(atob(content),c=>c.charCodeAt(0))}catch{return json({error:'사진 형식을 확인해주세요.'},400)}
    const hash=await digest(raw),claim=await rpc('pildam_claim',{p_hash:hash});if(claim.state==='done')return json({text:claim.text,quality:claim.quality??null,cached:true,provider:'Google Cloud Vision'});if(claim.state==='limit')return json({error:'이번 달 분석 한도 10,000회에 도달해 추가 비용 방지를 위해 멈췄어요.'},429);if(claim.state!=='claimed')return json({error:'같은 사진을 읽고 있어요. 잠시 후 다시 확인해주세요.'},409);
    try{const r=await fetcher('https://vision.googleapis.com/v1/images:annotate',{method:'POST',headers:{'Content-Type':'application/json','X-Goog-Api-Key':env.GOOGLE_VISION_API_KEY},body:JSON.stringify({requests:[{image:{content},features:[{type:'DOCUMENT_TEXT_DETECTION'}],imageContext:{languageHints:['ko']}}]}),signal:AbortSignal.timeout(45000)}),out=await r.json(),entry=out.responses?.[0];if(!r.ok||entry?.error)throw Error('인식 서비스에 문제가 생겼어요.');const text=entry.fullTextAnnotation?.text||'',quality=visualQuality(entry.fullTextAnnotation);await rpc('pildam_finish',{p_hash:hash,p_text:text,p_quality:quality,p_success:true});return json({text,quality,cached:false,provider:'Google Cloud Vision'});}catch{await rpc('pildam_finish',{p_hash:hash,p_text:null,p_quality:null,p_success:false});return json({error:'인식 서버가 응답하지 않았어요. 자동 재시도하지 않았습니다.'},502);}
  }
  return async req=>{const origin=req.headers.get('Origin');if(!env.APP_ORIGIN||origin!==env.APP_ORIGIN)return json({error:'허용되지 않은 앱 주소입니다.'},403);const h={'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'content-type, x-app-token, x-pildam-session','Access-Control-Max-Age':'600','Vary':'Origin'};if(req.method==='OPTIONS')return new Response(null,{status:204,headers:h});let r;try{r=await handle(req)}catch{r=json({error:'서비스를 일시적으로 이용할 수 없어요. 잠시 후 다시 시도해주세요.'},503)}for(const[k,v]of Object.entries(h))r.headers.set(k,v);return r;};
}
